assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: true
  test: true
instrument: CE01ISSM-MFD35-02-PRESFA000
stream:
  method: telemetered
  name: presf_abc_dcl_tide_measurement
workflow_config:
  schedule: 0 0 * * *
